name: Post a test message when a PR is opened
on:
  pull_request:
    types: [opened]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_modified: ${{ steps.changed-files-specific.outputs.any_modified }}
      changed_files: ${{ steps.changed-files-specific.outputs.all_changed_files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get changed files in the yaml folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            plumber/yaml/**
      - name: Print any_modified
        run: echo ${{ steps.changed-files-specific.outputs.any_modified }}

  build-and-update:
    needs: get-changed-files
    runs-on: ubuntu-latest
    if: needs.get-changed-files.outputs.any_modified == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build-image
        run: docker build . -t plumber
      - name: Run step if any file(s) in the yaml folder change
        run: |
          echo "One or more files in the yaml folder has changed."
          docker run -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} plumber client.py ${{ needs.get-changed-files.outputs.changed_files }}