name: Update server content based on tracked YAML files
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build-image
        run: docker build . -t plumber
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            plumber/yaml/**
      - name: Run step if any file(s) in the yaml folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the yaml folder has changed."
          docker run -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} client.py ${{ steps.changed-files-specific.outputs.all_changed_files }}"
