name: Update server content based on tracked YAML files
on:
  push:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      files_have_changed: ${{ steps.changed-files-specific.outputs.any_changed }}
      changed_files: ${{ steps.changed-files-specific.outputs.all_changed_files }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get changed files in the yaml folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            plumber/yaml/**

  build-and-update:
    needs: changed-files-specific
    runs-on: ubuntu-latest
    if: ${{ needs.changed-files-specific.outputs.files_have_changed }} == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build-image
        run: docker build . -t plumber
      - name: Run step if any file(s) in the yaml folder change
        run: |
          echo "One or more files in the yaml folder has changed."
          docker run -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} plumber client.py ${{ needs.changed-files-specific.outputs.changed_files }}
